# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
