# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20170218_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='body',
            new_name='data',
        ),
    ]
